services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: graincircuit-web:prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: graincircuit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
