name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod \
            -t ${{ secrets.DOCKER_USERNAME }}/graincircuit-web:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/graincircuit-web:latest

  collectstatic:
    name: Collect Static Files
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Run collectstatic
        run: |
          docker run --rm \
            -e AZURE_ACCOUNT_NAME="${{ secrets.AZURE_ACCOUNT_NAME }}" \
            -e AZURE_ACCOUNT_KEY="${{ secrets.AZURE_ACCOUNT_KEY }}" \
            -e AZURE_STATIC_CONTAINER="${{ secrets.AZURE_STATIC_CONTAINER }}" \
            -e USE_AZURE_STORAGE="${{ secrets.USE_AZURE_STORAGE }}" \
            ${{ secrets.DOCKER_USERNAME }}/graincircuit-web:latest \
            python manage.py collectstatic --noinput --verbosity 3
